version: "3.9"

services:
  csvserver:
    volumes:
      - ./inputFile:/csvserver/inputdata:z
    env_file:
      - csvserver.env
    image: "docker.io/infracloudio/csvserver"
    ports:
      - "9393:9300"

  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - csvserver
