global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'csvserver'
    scrape_interval: 15s
    static_configs:
      - targets: ['csvserver:9300']

